<?php

class IndexController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->view->THIS_CONTROLLER = 'Index';

    }

    /**
     * 设置标题
     * @param $dispatcher \Phalcon\Dispatcher
     */
    public function beforeExecuteRoute($dispatcher)
    {
        /**
         * 设置页面 标题
         */
        if($dispatcher->getActionName() == 'index'){
            $this->tag->setTitle($this->L('index_title'));
        }

    }

    public function indexAction()
    {
        
    }

}

