<?php
/**
 * Created by PhpStorm.
 * User: zc
 * Date: 2016/5/12
 * Time: 11:11
 */

namespace App\Http\Controllers\Admin;


class AuthController extends CommonController
{
    public function _init()
    {
        parent::_init(); // TODO: Change the autogenerated stub

        $this->middleware('AdminAuth');
    }
}