<?php
/**
 * Created by PhpStorm.
 * User: zc
 * Date: 2016/5/12
 * Time: 9:52
 */
namespace App\Http\Controllers\Admin;

use App\Model\Index;
use Illuminate\Http\Request;

class CarouselController extends AuthController
{
    //轮播图首页
    public function _init()
    {
        parent::_init(); // TODO: Change the autogenerated stub
        view()->share('MENU_ELEMENT', true);

    }

    public function getIndex()
    {
        $carousels = Index::where('id', '>', 0)->paginate(10);

        return view('admin.carousel.index', ['carousels' => $carousels, 'active' => 'carousels']);
    }

    public function getAdd(Request $request)
    {

        return view('admin.carousel.add', ['active' => 'carousels']);
    }

    public function postAdd(Request $request)
    {
        $index = new Index();
        $index->description = $request->input('description', '');
        $index->type = $request->input('type', '');;
        $index->title = $request->input('title', '');
        $imgurl = $request->input('mortgaged-img-url', array());

        if (empty($imgurl)) {
            return $this->jump('Image was not upload!', '/admin/carousel/add');
        }
        $index->imgurl = $imgurl[0];
        $index->href = $request->input('href');

        if ($index->save())
            $message = 'Add Success!';
        else
            $message = 'Failed add!';

        return $this->jump($message, '/admin/carousel/add');

    }

    public function getDel(Request $request)
    {
        $id = $request->input('id', 0);

        $del = Index::where('id', $id)->update(
            array('status' => 0)
        );

        if ($del) {

            return $this->jump('Software Delete Success', '/admin/carousel/index');
        } else {
            return back();
        }
    }

    public function getActive(Request $request)
    {
        $id = $request->input('id', 0);

        $del = Index::where('id', $id)->update(
            array('status' => 1)
        );

        if ($del) {
            return redirect('/admin/carousel/index');
        } else {
            return back();
        }
    }

    public function getUpdate(Request $request)
    {

        $id = $request->input('id', 0);

        $index = Index::where('id', $id)->first();
        if (empty($index)) {
            return $this->jump('Not found', '/admin/carousel/index');
        }

        return view('admin.carousel.update', ['data' => $index]);
    }

    public function postUpdate(Request $request)
    {
        $index = Index::where('id', $request->input('id'))->find(1);
        if (empty($index)) {
            return $this->jump('The data not exists!', '/admin/carousel/index');;
        }
        $index->description = $request->input('description', '');
        $index->type = $request->input('type');
        $index->imgurl = $request->input('imgurl');
        $index->href = $request->input('href');
        $index->sort = $request->input('sort');


        if ($index->save())
            return $this->jump('Update Success', '/admin/carousel/index');
        else
            return $this->jump('Update Failed', '/admin/carousel/index');
    }
}