<?php
/**
 * Created by PhpStorm.
 * User: zc
 * Date: 2016/5/12
 * Time: 9:52
 */
namespace App\Http\Controllers\Admin;

use App\Model\Index;
use Illuminate\Http\Request;

class CarouselController extends AuthController
{
    //轮播图首页
    public function _init()
    {
        parent::_init(); // TODO: Change the autogenerated stub
        view()->share('MENU_ELEMENT',true);

    }

    public function getIndex()
    {
        $carousels = Index::where('id','>',0)->paginate(10);

        return view('admin.carousel.index',['carousels'=>$carousels,'active'=>'carousels']);
    }

    public function getAdd(Request $request)
    {

    }

    public function getDel(Request $request)
    {
        $id = $request->input('id',0);

        $del = Index::where('id',$id)->update(
            array('status'=>0)
        );

        if($del){
            return redirect('/admin/carousel/index');
        }else{
            return back();
        }
    }

    public function getActive(Request $request)
    {
        $id = $request->input('id',0);

        $del = Index::where('id',$id)->update(
            array('status'=>1)
        );

        if($del){
            return redirect('/admin/carousel/index');
        }else{
            return back();
        }
    }

    public function getUpdate(Request $request){

    }

    public function postUpdate(Request $request)
    {

    }
}