<?php
/**
 * Created by PhpStorm.
 * User: zhangcheng
 * Date: 16/9/5
 * Time: 下午2:56
 */
namespace App\Action;


class ReadAction extends CommonAction
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $action_name = strtolower ( ACTION_NAME );
        switch ($action_name) {
            case 'index' :
                $this->assign ( "website_title", "阅读" );
                break;
        }
    }

    public function index()
    {
        $article = M ( "Read" );
        $all = $article->where ( "isdel=0" )->count ();

        $page = new \Think\Page( $all, 4);
        $page->setConfig ( 'header', '篇文章' );
        $page->setConfig ( 'prev', 'Prev Page' );
        $page->setConfig ( 'next', 'Next Page' );
        $show = $page->show ();
        $res = $article->query ( "select * from vip_read where isdel = 0 order by id desc limit {$page->firstRow},{$page->listRows}" );
        $this->assign ( "read",  $res );
        $this->assign ( "page", $show );
        $this->display ();
    }

    public function create()
    {
        $this->formLoginCheck ();

        if(IS_POST) {

            $data = I('post.');
            if($data['img_url']==''){
                $data['img_url'] = $data['mortgaged-img-url'];
            }

            $data['uid'] = $_SESSION ["Auth"] ["id"];
            $add = M('read')->add($data);

            if($add)
            {
                $this->actionReturn(1,'添加成功','/read');
            }else{
                $this->actionReturn(0,'添加失败','/read/create');
            }

        }else{

            $this->assign('website_title','添加阅读');
            $this->display ();
        }
    }


    public function del()
    {
        $id = I('get.id',0,'int');
        $this->formLoginCheck ();

        $del = M('read')->where(['id'=>$id,'uid'=>$_SESSION ["Auth"] ["id"]])->save(['isdel'=>1]);

        if($del === false)
        {
            $this->formErrorReferer('删除失败');
        }else{
            $this->formSuccess('删除成功','/read');
        }
    }


    public function edit()
    {
        $this->formLoginCheck ();

        if(IS_POST)
        {
            $id = I('post.id',0,'int');
            $data = I('post.');
            $update = M('read')->where(['id'=>$id,'uid'=>$_SESSION ["Auth"] ["id"]])->save($data);
            if($update!==false)
            {
                $this->formSuccess('修改成功','/read');
            }else{
                $this->formErrorReferer('修改失败');
            }
        }else{
            $id = I('get.id',0,'int');

            $data = M('read')->where(['id'=>$id,'uid'=>$_SESSION ["Auth"] ["id"]])->find();
            if(empty($data))
            {
                $this->_empty();
            }
            $this->assign('website_title','修改阅读');
            $this->display();
        }


    }

}